# -*- coding: utf-8 -*-
"""spacy_postags_lemmas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177V0KgR9RSUV19hwtPdl2okJ8mmIOmkQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U pip setuptools wheel
# %pip install -U spacy
!python -m spacy download fr_dep_news_trf

# %pip install stanza

# %pip install spacy-lefff

# %pip install datasets

import pandas as pd
import json

import spacy
# from datasets import load_dataset
import stanza

nlp = spacy.load("fr_dep_news_trf")
import fr_dep_news_trf
nlp = fr_dep_news_trf.load()

from spacy_lefff import LefffLemmatizer, POSTagger
from spacy.language import Language

@Language.factory('french_lemmatizer')
def create_french_lemmatizer(nlp, name):
    return LefffLemmatizer(after_melt=True, default=True)

@Language.factory('melt_tagger')
def create_melt_tagger(nlp, name):
    return POSTagger()

nlpl = spacy.load('fr_dep_news_trf')
nlpl.add_pipe('melt_tagger', after='parser')
nlpl.add_pipe('french_lemmatizer', after='melt_tagger')

# ds = load_dataset("maximoss/sick-fr-mt", split="test")

stanza.download('fr') # download French model
nlps = stanza.Pipeline('fr') # initialize French neural pipeline
# nlps = stanza.Pipeline('fr', tokenize_pretokenized=True) # initialize French neural pipeline with text already tokenised

with open('rte3_test_postags_lemmas_spacy.jsonl', 'w', encoding='utf-8') as f, open('rte3_test_input.txt', 'r', encoding='utf-8') as ds, open('rte3_test_input.txt', 'r', encoding='utf-8') as dfil:
  initial_sentences = dfil.readlines()
  for index, line in enumerate(ds):
    premise = nlp(line.strip())
    result=[[w.text, w.lemma_, w.pos_, str(w.morph), w.tag_, w.dep_] for w in premise if w.text!="'"]
    json.dump({'id': (index+1), 'sentence': initial_sentences[index].strip(), 'pos_lemma': result}, f)
    f.write("\n")

with open('rte3_test_postags_lemmas_lefff.jsonl', 'w', encoding='utf-8') as f, open('rte3_test_input.txt', 'r', encoding='utf-8') as ds, open('rte3_test_input.txt', 'r', encoding='utf-8') as dfil:
  initial_sentences = dfil.readlines()
  for index, line in enumerate(ds):
    sent_lefff = nlpl(line.strip())
    result=[[w.text, w._.lefff_lemma, w._.melt_tagger, str(w.morph)] for w in sent_lefff if w.text!="'"]
    json.dump({'id': (index+1), 'sentence': initial_sentences[index].strip(), 'pos_lemma': result}, f)
    f.write("\n")

with open('rte3_test_postags_lemmas_stanza.jsonl', 'w', encoding='utf-8') as f, open('rte3_test_input.txt', 'r', encoding='utf-8') as ds, open('rte3_test_input.txt', 'r', encoding='utf-8') as dfil:
  initial_sentences = dfil.readlines()
  for index, line in enumerate(ds):
    sent_stanza = nlps(line.strip())
    result_stanza=[[w.text, w.lemma, w.pos, w.feats, w.deprel] for sent in sent_stanza.sentences for w in sent.words if w.text!="'"]
    json.dump({'id': (index+1), 'sentence': initial_sentences[index].strip(), 'pos_lemma': result_stanza}, f)
    f.write("\n")